Update

diff --git a/gui b/gui
--- a/gui
+++ b/gui
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 
-if [[ "$1" ]]; then
-  yt_trans_file="$1"
-else
-  yt_trans_file=transcript.pt.srt
+if ! type yad  >/dev/null; then
+  echo 'error: need yad to gui' >&2
+  exit 1
 fi
 
-yt_trans_txt=$(awk -f format.awk "$yt_trans_file")
+if [[ -z "$1" ]]; then
+  echo 'error: no file'
+  exit 1
+fi
+
+str_file="$1"
+str_txt=$(awk -f format.awk "$str_file")
 
 # Clipboard line on click time cell
 clipboard() {
@@ -15,7 +20,7 @@ clipboard() {
 }
 export -f clipboard
 
-# # Show yad
+# Show yad
 yad --list \
   --title=Transcrição \
   --editable --editable-cols=2 \
@@ -23,4 +28,4 @@ yad --list \
   --regex-search \
   --dclick-action='bash -c "clipboard \"%s\""' \
   --column=Tempo --column=Frase \
-  < <(awk -F ' - ' '{ print $1 "\n" $2 }' <<< $yt_trans_txt)
+  < <(awk -F ' = ' '{ print $1 "\n" $2 }' <<< $str_txt)
diff --git a/ytt b/ytt
--- a/ytt
+++ b/ytt
@@ -4,48 +4,65 @@
 
 set -e
 
-yt_trans_file=transcript.pt.srt
-yt_trans_file_format=transcript.txt
-yt_trans_lang=pt
+cwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+lang=pt
 
-# Check file exist
-if [[ -f "$yt_trans_file" ]]; then
-  read -rp 'File exist overwrie [y/N]: ' opc
-
-  if [[ $opc =~ [Yy] ]]; then
-    yt_trans_file_overwrite=true
-  fi
+# Check yt-dlp
+if ! type yt-dlp >/dev/null; then
+  echo 'error: need yt-dlp' >&2
+  exit 1
 fi
 
 # Check url
 if [[ $1 ]]; then
-  yt_url="$1"
+  url="$1"
 else
   echo 'error: need url' >&2
   exit 1
 fi
 
-# Check yt-dlp
-if ! type yt-dlp  >/dev/null; then
-  echo 'error: need yt-dlp' >&2
+# Get video title
+title=$(yt-dlp --restrict-filenames --print filename -o "%(title).20s" "$url" 2>/dev/null)
+
+# Check title
+if [[ -z "$title" ]]; then
+  echo 'error: could not get video title' >&2
   exit 1
 fi
 
+str_file="$title.$lang.srt"
+txt_file="$title.txt"
+
+# Check file exist
+if [[ -f "$str_file" ]]; then
+  read -rp 'File exist overwrie [y/N]: ' opc
+  if [[ $opc =~ [Yy] ]]; then
+    str_file_overwrite=true
+  fi
+fi
+
 # Get transcript
-if [[ ! -f "$yt_trans_file" ]] || [[ $yt_trans_file_overwrite == 'true' ]]; then
+if [[ ! -f "$str_file" ]] || [[ $str_file_overwrite == 'true' ]]; then
   yt-dlp \
     --skip-download \
     --sub-format srt \
-    --sub-lang $yt_trans_lang \
+    --sub-lang $lang \
     --write-subs \
     --write-auto-subs \
     --quiet \
-    --output "transcript" \
-    "$yt_url"
+    --no-warnings \
+    --progress-template "Downloading: %(progress._percent_str)s" \
+    --js-runtimes node \
+    --remote-components ejs:github \
+    --output "$title" \
+    "$url"
 fi
 
 # Get format transcript from
-yt_trans_txt=$(awk -f format.awk "$yt_trans_file")
+str_txt=$(awk -f "$cwd/format.awk" "$str_file")
+
+# Transform txt format
+echo "$str_txt" > "$txt_file"
 
 read -rp '
 Escolha uma opção:
@@ -56,19 +73,9 @@ q) Quit
 
 Opção: ' opc
 
-# Transform txt format
-echo "$yt_trans_txt" > "$yt_trans_file_format"
-
 case "$opc" in
-  p) echo "$yt_trans_txt" ;;
-  o) $EDITOR $yt_trans_file_format ;;
-  g)
-    if type yad  >/dev/null; then
-      ./gui "$yt_trans_file"
-    else
-      echo 'error: need yad to gui' >&2
-      exit 1
-    fi
-    ;;
+  p) echo "$str_txt" ;;
+  o) $EDITOR "$txt_file" ;;
+  g) $cwd/gui "$str_file" ;;
   q) exit 0 ;;
 esac
